name: deploy to lambda

on: [push]

jobs:
  deploy_source:
    name: build and deploy lambda

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: npm install and build
        run: |
          npm run build

      - name: zip
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r ./bundle.zip ./

      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-3
          function_name: tdupoiron_github_webhook_lambda
          zip_file: github_webhook_lambda.zip